version: "3"

services:
  sbtm-db:
    image: mysql:5.7
    container_name: sbtm-db
    environment:
      - MYSQL_ROOT_PASSWORD=Password01!
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
    networks:
      sbtm_demo:
        aliases:
          - sbtm-db
    ports:
      - 3306:3306
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 20s
    #   retries: 10
  sbtm-web:
    image: meirwa/spring-boot-tomcat-mysql-app
    container_name: sbtm-web
    environment:
      - DB_URL=sbtm-db
      - DB_PORT=3306
      - DB_NAME=demo
      - DB_USER=demo
      - DB_USER_PASS=demo
    networks:
      sbtm_demo:
        aliases:
          - sbtm-web
    ports:
      - 8080:8080
    # depends_on:
    #   db:
    #     condition: service_healthy
  sbtm-adminer:
    image: adminer:4.6.2
    container_name: sbtm-adminer
    networks:
      sbtm_demo:
        aliases:
          - sbtm-adminer
    ports:
      - 8081:8080
    # depends_on:
    #   db:
    #     condition: service_healthy

networks:
  sbtm_demo:
