apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: sbtm-adminer
  name: sbtm-adminer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sbtm-adminer
    spec:
      containers:
      - image: 10.0.0.5/guhuajun/adminer:4.6.2
        name: sbtm-adminer
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - dcelab-dce02
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: sbtm-adminer
  name: sbtm-adminer
spec:
  type: NodePort
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8080
    nodePort: 32001
  selector:
    io.kompose.service: sbtm-adminer
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: sbtm-db
  name: sbtm-db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sbtm-db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: demo
        - name: MYSQL_PASSWORD
          value: demo
        - name: MYSQL_ROOT_PASSWORD
          value: Password01!
        - name: MYSQL_USER
          value: demo
        image: 10.0.0.5/guhuajun/mysql:5.7
        name: sbtm-db
        ports:
        - containerPort: 3306
        resources: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - dcelab-dce02
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: sbtm-db
  name: sbtm-db
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: sbtm-db
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: sbtm-web
  name: sbtm-web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sbtm-web
    spec:
      containers:
      - env:
        - name: DB_NAME
          value: demo
        - name: DB_PORT
          value: "3306"
        - name: DB_URL
          value: sbtm-db
        - name: DB_USER
          value: demo
        - name: DB_USER_PASS
          value: demo
        image: 10.0.0.5/meirwa/spring-boot-tomcat-mysql-app
        name: sbtm-web
        ports:
        - containerPort: 8080
        resources: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - dcelab-dce02
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: sbtm-web
  name: sbtm-web
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 32002
  selector:
    io.kompose.service: sbtm-web
status:
  loadBalancer: {}
