apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: sbtm-db
  name: sbtm-db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sbtm-db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: demo
        - name: MYSQL_PASSWORD
          value: demo
        - name: MYSQL_ROOT_PASSWORD
          value: Password01!
        - name: MYSQL_USER
          value: demo
        image: mysql:5.7
        name: sbtm-db
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
